# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Satish Upadhyaya
tagline:          'Personal Website'
description:      '/home/SatishUpadhyaya'
#url:              http://hyde.getpoole.com

author:
  name:           'Satish Upadhyaya'
  url:            https://github.com/satishupadhyaya

# Site Settings
pagination:
  enabled: true
  per_page: 7
  permalink: '/page/:num/'
  limit: 0
  title: ':title Page #:num'
  sort_field: 'date'
  sort_reverse: false
  
excerpt_separator: <!--excerpt_ends-->

# Custom vars
version:          2.1.0

plugins:
  - jekyll-gist

# repository:           https://github.com/satishupadhyaya/satishupadhyaya.github.io

# Collections
collections:
    supplements:
        output: true